{{- if .Values.ezua.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "llamafactory.fullname" . }}
  labels:
    {{- include "llamafactory.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | quote }}
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway | quote }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "llamafactory.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
      # Gradio uses WebSockets for the training queue,
      # so we must allow WS upgrades and long timeouts.
      timeout: 86400s
{{- end }}
